/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
  public String getGreeting() {
    return "Hello World, this is a Test!";
  }

  public static void main(String[] args) {
    ArrayList<String> listOne = new ArrayList();
  
    System.out.println(new App().getGreeting());
  }
}
